In [36]:
import pandas as pd
import numpy as np
import json
import requests

In [37]:
def get_data(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        players = pd.DataFrame(data['elements'])
        return players
    except requests.exceptions.RequestException as e:
            print(f"There was an error: {e} while retrieving data")
        
df = get_data("https://fantasy.premierleague.com/api/bootstrap-static/")
df

    
# top_level = ['events', 'game_settings', 'phases', 'teams', 'elements', 'element_stats', 'element_types']

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,0.0,0.0,438098,0,0,-1,1,0,3,0.0,...,137,82,651,294,664,303,632,280,0.00,0.00
1,100.0,100.0,205651,0,0,-2,2,0,4,1.8,...,32,14,299,38,439,45,211,37,0.74,0.00
2,100.0,100.0,226597,-1,1,1,-1,1,2,2.5,...,75,5,217,64,49,6,15,5,1.04,0.28
3,100.0,75.0,219847,0,0,0,0,1,4,2.5,...,12,4,222,30,45,15,37,8,1.00,0.27
4,0.0,0.0,463748,0,0,0,0,0,1,0.0,...,633,65,422,47,494,54,548,67,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,100.0,100.0,510362,0,0,-2,2,1,2,2.5,...,567,146,112,29,283,93,391,141,1.10,0.12
674,50.0,50.0,560248,0,0,0,0,0,2,0.0,...,660,206,448,169,519,187,410,149,0.00,0.00
675,NaN,NaN,509291,0,0,0,0,0,3,0.5,...,232,148,326,161,343,168,595,254,1.24,0.00
676,NaN,NaN,463212,0,0,0,0,0,3,0.5,...,123,75,329,164,433,217,588,250,0.50,0.00
677,NaN,NaN,517179,-1,1,-1,1,0,2,0.0,...,676,222,376,129,453,152,406,147,0.00,0.00

In [39]:
df = pd.read_csv("players.csv")
df.head()
df.columns

Index(['id', 'name', 'now_cost', 'position', 'team',
       'chance_of_playing_next_round', 'expected_goals_per_90', 'creativity',
       'event_points', 'news', 'direct_freekicks_order',
       'expected_goals_conceded', 'chance_of_playing_this_round',
       'transfers_in', 'status', 'region', 'transfers_out', 'form_rank',
       'form_rank_type', 'goals_conceded', 'dreamteam_count',
       'transfers_out_event', 'threat_rank', 'points_per_game_rank',
       'goals_scored', 'points_per_game_rank_type', 'cost_change_start_fall',
       'goals_conceded_per_90', 'cost_change_event', 'cost_change_start',
       'cost_change_event_fall', 'own_goals', 'expected_goal_involvements',
       'now_cost_rank', 'threat', 'creativity_rank', 'news_added', 'bonus',
       'selected_rank_type', 'expected_assists', 'selected_rank', 'form',
       'clean_sheets_per_90', 'influence_rank', 'minutes', 'assists',
       'ict_index_rank_type', 'in_dreamteam', 'selected_by_percent',
       'influence_rank_type', 'ep_next', 'points_per_game', 'yellow_cards',
       'influence', 'starts', 'expected_goal_involvements_per_90',
       'penalties_missed', 'expected_goals', 'web_name', 'threat_rank_type',
       'total_points', 'penalties_saved', 'saves_per_90',
       'expected_assists_per_90', 'clean_sheets', 'transfers_in_event',
       'penalties_order', 'value_season', 'creativity_rank_type',
       'now_cost_rank_type', 'ict_index', 'ict_index_rank', 'saves',
       'starts_per_90', 'bps', 'value_form', 'expected_goals_conceded_per_90',
       'red_cards', 'corners_and_indirect_freekicks_order', 'ep_this'],
      dtype='object')

In [40]:
df["position"].unique()

array(['MID', 'FWD', 'DEF', 'GKP'], dtype=object)